[package]
name = "stylus_benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
jit = { path = "../../jit/" }
wasmer = { path = "../wasmer/lib/api/" }
wasmer-compiler-cranelift = { path = "../wasmer/lib/compiler-cranelift/" }
